### ISSUE TITLE
Mute works only if default input source is selected

### ISSUE THREAD

**Issue by alex-exe** [satrik/toggleMute#1]
The application works perfectly when you are using the built-in Input source.
However, if any bluetooth headphones are used it does not mute the microphone, despite showing mute icon on the bars.

Can you please extend it to work with currently selected Input device?

Nice app! Really looking forward using it, but have a fear of being unmute by mistake when bluetooth device is connected...

**Comment by satrik** [comment]
hey @alex-exe, I use it with different bluetooth headsets and don't have any issues. 
You have to select the headset as default input/output source in the system settings, as the app just mute/unmute the default microphone.

**Comment by mrtysn** [comment]
Hi @satrik,

I wish this information was more visible. Luckily, I was able to notice it before I got myself into an embarrassing situation. Here is what happened:
- Since I installed this application, I've been keeping myself unmuted during work calls via Teams.
- I set up a custom global hotkey for ToggleMute and I control my input audio level only through that.
- I saw the red mute icon on menu bar, feeling private, and I sneezed. 
- I have closed captions turned on. Somehow, Teams interpreted that sound as a 'sure' and alarms start ringing in my head, wondering if I ever said anything that I shouldn't have while I was only muted by ToggleMute, as it was clearly detecting input from my side.
- I go into audio settings and realize that I have 4 input audio sources and this is only toggling the default one, which was not being used by Teams.
- Come find this issue and type this message, hoping someone else can be saved from such potential situations.

If you can already grab the list of available input sources through an API, listing them and saying that 'only the default one is being affected' as a small disclaimer, I think that would do the trick.

Thank you for making and sharing this application :)
